### PR TITLE
fix(auth): require session on certain pages

### LINKED ISSUE #126: [Bug] Pages can still be accessed when not logging in
**Describe the bug**
Currently, the following pages can still be accessed without requiring users to log in. 
- Resume Page
- Events Page
- Opportunities Page

**To Reproduce**
1. Go to `/resume` or `/opportunities` or `/events`
2. Click on 'Sign Out'
3. (Optional) Can try to refresh the page, and the pages would still be accessible. 

**Expected behavior**
User should be required to log in when trying to access those page if they haven't logged in yet. 

**Additional context**
N/A

### PR DESCRIPTION
**Pull request by spierceVR**
fix #126

Requires user to be logged in to view:
- Resume Page
- Events Page
- Opportunities Page
- Other pages that previously required authentication

If they are not logged in and attempt to view these routes, an error message is displayed explaining that they must be signed into view these pages, along with a button that links them to the sign in page.

Todo:
- [x] fix secured pages momentarily showing while loading

### CODE REVIEW

**Comment by DedsecKnight** [comment]
Can u add the restrictions to these pages as well? 
- [Create Typeform](https://github.com/acmutd/portal-next/blob/next/apps/portal/pages/opportunities/create.tsx)
- [Edit Typeform view](https://github.com/acmutd/portal-next/blob/next/apps/portal/pages/opportunities/edit/index.tsx)
- [Edit Typeform Single App](https://github.com/acmutd/portal-next/blob/next/apps/portal/pages/opportunities/edit/%5Bid%5D.tsx)

**Comment by spierceVR** [comment]
> Can u add the restrictions to these pages as well?
> 
> * [Create Typeform](https://github.com/acmutd/portal-next/blob/next/apps/portal/pages/opportunities/create.tsx)
> * [Edit Typeform view](https://github.com/acmutd/portal-next/blob/next/apps/portal/pages/opportunities/edit/index.tsx)
> * [Edit Typeform Single App](https://github.com/acmutd/portal-next/blob/next/apps/portal/pages/opportunities/edit/%5Bid%5D.tsx)

Should be resolved now

**Comment by DedsecKnight** [comment]
Can you add your changes to these files as well? 
- [Event QR Code Generator](https://github.com/acmutd/portal-next/blob/126-require-session/apps/portal/pages/events/%5Bslug%5D/qrcode.tsx)
- [Create Typeform Application](https://github.com/acmutd/portal-next/blob/126-require-session/apps/portal/pages/opportunities/create.tsx)

**Review by DedsecKnight — CHANGES_REQUESTED** [review]
Can you add your changes to these files as well? 
- [Event QR Code Generator](https://github.com/acmutd/portal-next/blob/126-require-session/apps/portal/pages/events/%5Bslug%5D/qrcode.tsx)
- [Create Typeform Application](https://github.com/acmutd/portal-next/blob/126-require-session/apps/portal/pages/opportunities/create.tsx)

**Review by DedsecKnight — APPROVED** [review]

**Pull request merged**
