### PR TITLE
add cards for active applications on opportunities page

### PR DESCRIPTION
**Pull request by Balstun**

### CODE REVIEW

**Comment by DedsecKnight** [comment]
`pages/opportunities` is supposed only have the `index.tsx` file. Everything else need to go to `components` folder because they are not pages.

**Comment by akevinge** [comment]
Any particular reason for adding babel? I did not notice a performance difference when I removed it. Would prefer to stick with SWC if possible.

**Comment by DedsecKnight** [comment]
The reason has to do with the fact that TypeGraphQL uses decorators, which is something SWC did not support when we start portal-v2. If it supports that now, we can definitely switch it back.

**Review by DedsecKnight — APPROVED** [review]

**Review by akevinge — APPROVED** [review]
Instead of adding different SVG files for black and white, we can put the SVG into JSX and pass in the fill property. See an example [here](https://github.com/acmutd/portal-next/blob/next/apps/portal/icons/CameraIcon.tsx). It doesn't matter a lot, but I'd rather keep SVG's in code because they're easier to customize than loading them in image tags.

**Pull request merged**
